Repository PQCA/sonar-cryptography, pull requests merged in 2024-09, with the labels that each got.

#129 Fetaure/fix python tests
  python/src/main/java/com/ibm/plugin/rules/detection/mac/PycaMAC.java
  python/src/main/java/com/ibm/plugin/rules/detection/padding/PycaPadding.java
  python/src/main/java/com/ibm/plugin/rules/detection/symmetric/PycaCipher.java
  python/src/main/java/com/ibm/plugin/translation/translator/contexts/PycaCipherContextTranslator.java
  python/src/main/java/com/ibm/plugin/translation/translator/contexts/PycaMacContextTranslator.java
  python/src/main/java/com/ibm/plugin/translation/translator/contexts/PycaPrivateKeyContextTranslator.java
  python/src/test/files/rules/detection/mac/PycaHMACTestFile.py
  python/src/test/files/rules/detection/mac/PycaPoly1305TestFile.py
  python/src/test/files/rules/detection/padding/PycaPaddingTestFile.py
  python/src/test/files/rules/detection/symmetric/PycaCipher1TestFile.py
  python/src/test/files/rules/detection/symmetric/PycaCipher2TestFile.py
  python/src/test/files/rules/detection/wrapping/PycaWrappingTestFile.py
  python/src/test/files/rules/detection/wrapping/PycaWrappingWithPaddingTestFile.py
  python/src/test/java/com/ibm/plugin/rules/detection/mac/CryptographyMacTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/mac/PycaHMACTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/mac/PycaPoly1305Test.java
  python/src/test/java/com/ibm/plugin/rules/detection/padding/PycaPaddingTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/symmetric/PycaCipher1Test.java
  python/src/test/java/com/ibm/plugin/rules/detection/symmetric/PycaCipher2Test.java
  python/src/test/java/com/ibm/plugin/rules/detection/wrapping/PycaWrappingTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/wrapping/PycaWrappingWithPaddingTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveImportedStructTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveInnerFunctionCallTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveNameTypeAndValuesTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveScopeValuesTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveValuesWithHooksTest.java
  python/src/test/java/com/ibm/plugin/utils/GenerateAssertsHelper.java
Labels: enhancement

#131 Fix/unit tests
  engine/src/test/java/com/ibm/engine/language/LanguageSupporterTest.java
  java/src/test/java/com/ibm/plugin/rules/detection/jca/keyspec/JcaPBEKeySpecTest.java
  mapper/src/main/java/com/ibm/mapper/model/collections/AbstractAssetCollection.java
  mapper/src/test/java/com/ibm/mapper/mapper/jca/JcaPBKDFMapperTest.java
  output/src/main/java/com/ibm/output/cyclondx/builder/AlgorithmComponentBuilder.java
  output/src/main/java/com/ibm/output/cyclondx/builder/AlgorithmVariant.java
  output/src/main/java/com/ibm/output/cyclondx/builder/KeyComponentBuilder.java
  output/src/test/java/com/ibm/output/cyclonedx/AlgorithmTest.java
  output/src/test/java/com/ibm/output/cyclonedx/TestBase.java
Labels: enhancement

#132 Fix/unit tests
  output/src/test/java/com/ibm/output/cyclonedx/AlgorithmTest.java
  output/src/test/java/com/ibm/output/cyclonedx/KeyTest.java
  output/src/test/java/com/ibm/output/cyclonedx/MergeDetectionLocationTest.java
  output/src/test/java/com/ibm/output/cyclonedx/ProtocolTest.java
  output/src/test/java/com/ibm/output/cyclonedx/TestBase.java
Labels: bug

#133 fix test in JCA
  mapper/src/main/java/com/ibm/mapper/model/algorithms/PBKDF2.java
  mapper/src/test/java/com/ibm/mapper/mapper/jca/JcaPBKDFMapperTest.java
Labels: bug

#134 Enhance CBOM generation
  java/src/test/java/com/ibm/plugin/rules/detection/jca/cipher/JcaCipherGetInstance1Test.java
  java/src/test/java/com/ibm/plugin/rules/detection/jca/cipher/JcaCipherGetInstance2Test.java
  java/src/test/java/com/ibm/plugin/rules/detection/jca/cipher/JcaCipherSecretKeySpecTest.java
  java/src/test/java/com/ibm/plugin/rules/detection/jca/keyagreement/JcaKeyAgreementGenerateSecretAlgorithmTest.java
  java/src/test/java/com/ibm/plugin/rules/detection/jca/keygenerator/JcaKeyGeneratorGetInstanceTest.java
  java/src/test/java/com/ibm/plugin/rules/detection/jca/keygenerator/JcaKeyGeneratorInitTest.java
  java/src/test/java/com/ibm/plugin/rules/detection/jca/keyspec/JcaPBEKeySpecTest.java
  mapper/src/main/java/com/ibm/mapper/model/IPrimitive.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/AES.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/CMAC.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/ChaCha20Poly1305.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/HMAC.java
  mapper/src/main/java/com/ibm/mapper/model/functionality/Functionality.java
  output/src/main/java/com/ibm/output/cyclondx/CBOMOutputFile.java
  output/src/main/java/com/ibm/output/cyclondx/builder/IKeyComponentBuilder.java
  output/src/main/java/com/ibm/output/cyclondx/builder/KeyComponentBuilder.java
  output/src/main/java/com/ibm/output/cyclondx/builder/RelatedCryptoMaterialComponentBuilder.java
  output/src/main/java/com/ibm/output/util/Utils.java
  output/src/test/java/com/ibm/output/cyclonedx/KeyTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/aead/PycaAESGCMTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/aead/PycaChaCha20Poly1305Test.java
  python/src/test/java/com/ibm/plugin/rules/detection/fernet/PycaFernetDecryptTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/fernet/PycaFernetEncryptTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/fernet/PycaMultiFernetTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/kdf/PycaKBKDFCMACTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/symmetric/PycaCipher1Test.java
Labels: enhancement

#135 Password Based Encryption model
  java/src/test/java/com/ibm/plugin/rules/detection/bc/encapsulatedsecret/BcECIESKEMExtractorTest.java
  java/src/test/java/com/ibm/plugin/rules/detection/bc/encapsulatedsecret/BcECIESKEMGeneratorTest.java
  java/src/test/java/com/ibm/plugin/rules/detection/jca/keyspec/JcaPBEKeySpecTest.java
  java/src/test/java/com/ibm/plugin/rules/detection/jca/mac/JcaMacGetInstanceTest.java
  mapper/src/main/java/com/ibm/mapper/mapper/bc/BcPbeMapper.java
  mapper/src/main/java/com/ibm/mapper/mapper/jca/JcaAlgorithmMapper.java
  mapper/src/main/java/com/ibm/mapper/mapper/jca/JcaCipherMapper.java
  mapper/src/main/java/com/ibm/mapper/mapper/jca/JcaMacMapper.java
  mapper/src/main/java/com/ibm/mapper/mapper/jca/JcaPBKDFMapper.java
  mapper/src/main/java/com/ibm/mapper/mapper/jca/JcaPasswordBasedEncryptionMapper.java
  mapper/src/main/java/com/ibm/mapper/model/PBES1.java
  mapper/src/main/java/com/ibm/mapper/model/PBES2.java
  mapper/src/main/java/com/ibm/mapper/model/PKCS12PBE.java
  mapper/src/main/java/com/ibm/mapper/model/PasswordBasedEncryption.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/PBKDF1.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/PBKDF2.java
  mapper/src/test/java/com/ibm/mapper/mapper/jca/JcaCipherMapperTest.java
  mapper/src/test/java/com/ibm/mapper/mapper/jca/JcaMacMapperTest.java
  mapper/src/test/java/com/ibm/mapper/mapper/jca/JcaPBKDFMapperTest.java
  mapper/src/test/java/com/ibm/mapper/mapper/jca/JcaPasswordBasedEncryptionMapperTest.java
Labels: enhancement

#137 Update model
  mapper/src/main/java/com/ibm/mapper/model/algorithms/AES.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/AESWrap.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/ANSIX942.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/ANSIX963.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/BIKE.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/Blowfish.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/Camellia.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/ChaCha20.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/ClassicMcEliece.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/DES.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/DESedeWrap.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/DH.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/DSTU4145.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/ECDSA.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/EdDSA.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/FrodoKEM.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/HQC.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/IDEA.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/KMAC.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/Kalyna.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/Keccak.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/LMS.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/MD2.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/MD5.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/RC2.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/RC4.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/RSAKEM.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/SABER.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/SHA.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/SM2.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/SM4.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/SipHash.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/TripleDES.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/X25519.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/X448.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/XMSS.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/Xoodyak.java
  python/src/test/java/com/ibm/plugin/rules/detection/keyagreement/PycaKeyAgreementTest.java
Labels: enhancement

#138 Update CBOM generation
  mapper/src/main/java/com/ibm/mapper/mapper/ssl/CipherSuiteMapper.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/DSA.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/RSA.java
  mapper/src/main/java/com/ibm/mapper/model/collections/AbstractAssetCollection.java
  output/src/main/java/com/ibm/output/cyclondx/CBOMOutputFile.java
  output/src/main/java/com/ibm/output/cyclondx/builder/ProtocolComponentBuilder.java
  output/src/main/java/com/ibm/output/util/Utils.java
  output/src/test/java/com/ibm/output/cyclonedx/AlgorithmTest.java
  output/src/test/java/com/ibm/output/cyclonedx/KeyTest.java
  output/src/test/java/com/ibm/output/cyclonedx/ProtocolTest.java
Labels: enhancement

#140 Fix Unit Tests in mapper and JCA
  java/src/test/java/com/ibm/plugin/rules/resolve/ResolveCallFromOtherClassTest.java
  mapper/src/main/java/com/ibm/mapper/model/PBES1.java
  mapper/src/test/java/com/ibm/mapper/mapper/ssl/CipherSuiteMapperTest.java
Labels: bug

#141 Fix issue #16
  engine/src/main/java/com/ibm/engine/language/java/JavaDetectionEngine.java
  java/src/test/files/rules/issues/Issue16TestFile.java
  java/src/test/files/rules/issues/NextParameterDependingRulesTestFile.java
  java/src/test/java/com/ibm/plugin/rules/issues/Issue16Test.java
  java/src/test/java/com/ibm/plugin/rules/issues/NextParameterDependingRulesTest.java
Labels: bug

#142 Fix issue #12
  engine/src/main/java/com/ibm/engine/detection/DetectionStore.java
  java/src/test/java/com/ibm/plugin/rules/issues/DuplicateDependingRules2Test.java
Labels: bug

#146 add nonce and iv to cbom output
  output/src/main/java/com/ibm/output/cyclondx/CBOMOutputFile.java
Labels: bug

#148 Fix JUnit issue with Python tests
  pom.xml
  python/src/test/java/com/ibm/plugin/rules/detection/aead/PycaAESGCMTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/aead/PycaChaCha20Poly1305Test.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/DSA/PycaDSANumbersTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/DSA/PycaDSASignTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/DiffieHellman/PycaDiffieHellmanGenerateTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/DiffieHellman/PycaDiffieHellmanNumbersTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/EllipticCurve/PycaEllipticCurveDeriveTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/EllipticCurve/PycaEllipticCurveKeyExchangeTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/EllipticCurve/PycaEllipticCurveNumbersTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/EllipticCurve/PycaEllipticCurveSign2Test.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/EllipticCurve/PycaEllipticCurveSignTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/EllipticCurve/PycaEllipticCurveVerifyTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/RSA/PycaRSADecryptTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/RSA/PycaRSANumbersTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/RSA/PycaRSASign1Test.java
  python/src/test/java/com/ibm/plugin/rules/detection/asymmetric/RSA/PycaRSASign2Test.java
  python/src/test/java/com/ibm/plugin/rules/detection/fernet/PycaFernetDecryptTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/fernet/PycaFernetEncryptTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/fernet/PycaMultiFernetTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/kdf/PycaConcatKDFHMACTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/kdf/PycaConcatKDFHashTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/kdf/PycaHKDFExpandTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/kdf/PycaHKDFTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/kdf/PycaKBKDFCMACTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/kdf/PycaKBKDFHMACTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/kdf/PycaPBKDF2Test.java
  python/src/test/java/com/ibm/plugin/rules/detection/kdf/PycaScryptTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/kdf/PycaX963KDFTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/keyagreement/PycaKeyAgreementTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/mac/PycaCMACTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/mac/PycaHMACTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/mac/PycaPoly1305Test.java
  python/src/test/java/com/ibm/plugin/rules/detection/padding/PycaPaddingTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/symmetric/PycaCipher1Test.java
  python/src/test/java/com/ibm/plugin/rules/detection/symmetric/PycaCipher2Test.java
  python/src/test/java/com/ibm/plugin/rules/detection/wrapping/PycaWrappingTest.java
  python/src/test/java/com/ibm/plugin/rules/detection/wrapping/PycaWrappingWithPaddingTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveAliasImportTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveImportedStructTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveInnerFunctionCallTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveNameTypeAndValuesTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveScopeValuesTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveValuesWithHooksTest.java
Labels: bug

#151 Fix issue report for python to SonarQube UI
  python/src/main/java/com/ibm/plugin/rules/detection/PythonBaseDetectionRule.java
Labels: bug

#152 SonarQube 10.6 support
  README.md
  docker-compose.yaml
  sonar-cryptography-plugin/pom.xml
Labels: bug

#153 Update Readme
  README.md
Labels: documentation

#155 Update maven.yml
  .github/workflows/maven.yml
Labels: github_actions

#163 create property for junit.jupiter.version
  pom.xml
Labels: enhancement
