Repository PQCA/sonar-cryptography, pull requests merged in 2024-08, with the labels that each got.

#95 update documentation
  CONTRIBUTING.md
  README.md
Labels: documentation

#99 update default key size in enricher, add bit as command to size values …
  enricher/src/main/java/com/ibm/enricher/algorithm/AESEnricher.java
  enricher/src/main/java/com/ibm/enricher/algorithm/DESEnricher.java
  enricher/src/main/java/com/ibm/enricher/algorithm/DHEnricher.java
  enricher/src/main/java/com/ibm/enricher/algorithm/DSAEnricher.java
  enricher/src/main/java/com/ibm/enricher/algorithm/IEnrichWithDefaultKeySize.java
  enricher/src/main/java/com/ibm/enricher/algorithm/RSAEnricher.java
  mapper/src/main/java/com/ibm/mapper/model/BlockSize.java
  mapper/src/main/java/com/ibm/mapper/model/DigestSize.java
  mapper/src/main/java/com/ibm/mapper/model/Seed.java
  mapper/src/main/java/com/ibm/mapper/model/TagLength.java
Labels: enhancement

#103 Update docs
  CONTRIBUTING.md
Labels: documentation

#106 Feature/update translation
  java/src/main/java/com/ibm/plugin/translation/reorganizer/UsualPerformActions.java
  java/src/main/java/com/ibm/plugin/translation/translator/contexts/JavaKeyContextTranslator.java
  java/src/test/java/com/ibm/plugin/rules/resolve/ResolveMethodCallTest.java
  mapper/src/main/java/com/ibm/mapper/ITranslator.java
  mapper/src/main/java/com/ibm/mapper/mapper/bc/BcAeadMapper.java
  mapper/src/main/java/com/ibm/mapper/mapper/jca/JcaAlgorithmMapper.java
Labels: enhancement

#112 pin supported SonarQube version in docker compose
  README.md
  docker-compose.yaml
Labels: bug, documentation

#113 Help and troubleshooting
  README.md
  docs/TROUBLESHOOTING.md
  docs/images/activate-more.png
  docs/images/activate-rule.png
  docs/images/add-language.png
  docs/images/blank-quality-profile.png
  docs/images/cbom.png
  docs/images/create-local-project.png
  docs/images/cryptography-inventory-rule.png
  docs/images/global-setting.png
  docs/images/issues.png
  docs/images/maven.png
  docs/images/overview.png
  docs/images/plugin-confirmation.png
  docs/images/project-settings.png
  docs/images/projects.png
  docs/images/provide-token.png
  docs/images/quality-profile-create.png
  docs/images/quality-profiles-setting.png
Labels: documentation

#117 fix mapper unit tests, update algorithm model
  mapper/src/main/java/com/ibm/mapper/mapper/pyca/PycaMacMapper.java
  mapper/src/main/java/com/ibm/mapper/model/Signature.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/MD2.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/MD5.java
  mapper/src/main/java/com/ibm/mapper/model/algorithms/SEED.java
  mapper/src/test/java/com/ibm/mapper/mapper/jca/JcaAlgorithmMapperTest.java
  mapper/src/test/java/com/ibm/mapper/mapper/jca/JcaMacMapperTest.java
  mapper/src/test/java/com/ibm/mapper/mapper/jca/JcaPBKDFMapperTest.java
  mapper/src/test/java/com/ibm/mapper/mapper/jca/JcaPRNGMapperTest.java
  mapper/src/test/java/com/ibm/mapper/mapper/jca/JcaPasswordBasedEncryptionMapperTest.java
  mapper/src/test/java/com/ibm/mapper/mapper/jca/JcaSignatureMapperTest.java
Labels: bug, enhancement
