Repository PQCA/sonar-cryptography, pull requests merged in 2024-07, with the labels that each got.

#33 Update readme
  README.md
Labels: documentation

#34 change sonar-plugin build config
  sonar-cryptography-plugin/pom.xml
Labels: bug

#35 GitHub Action deploying the plugin as a GitHub Package
  .github/workflows/maven-publish.yml
  docs/LANGUAGE_SUPPORT.md
  java/pom.xml
  java/src/test/java/com/ibm/plugin/ExportJavaRulesToJsonTest.java
  pom.xml
Labels: github_actions

#36 Fix Python test failing when upgrading `junit-jupiter-api`
  .github/workflows/maven.yml
  pom.xml
Labels: bug, dependencies, java

#45 Docs/update readme
  .github/img/activate_rules.png
  .github/img/project_qp.png
  .github/img/quality_profile.png
  README.md
  java/src/main/java/com/ibm/plugin/JavaScannerRuleDefinition.java
  java/src/main/resources/org/sonar/l10n/java/rules/java/Inventory.html
  java/src/main/resources/org/sonar/l10n/java/rules/java/Inventory.json
  python/src/main/java/com/ibm/plugin/PythonScannerRuleDefinition.java
  python/src/main/resources/org/sonar/l10n/python/rules/python/Inventory.html
  python/src/main/resources/org/sonar/l10n/python/rules/python/Inventory.json
  sonar-cryptography-plugin/pom.xml
  sonar-cryptography-plugin/src/main/java/com/ibm/plugin/CryptographyPlugin.java
  sonar-cryptography-plugin/src/main/java/com/ibm/plugin/OutputFileJob.java
  sonar-cryptography-plugin/src/test/java/com/ibm/plugin/PluginTest.java
Labels: documentation

#47 Update image in README
  .github/img/rules.png
  README.md
Labels: documentation

#57 Update Logging after sonar api change (9.15)
  engine/src/main/java/com/ibm/engine/language/java/JavaDetectionEngine.java
  engine/src/main/java/com/ibm/engine/language/java/JavaLanguageSupport.java
  engine/src/main/java/com/ibm/engine/language/java/JavaLanguageTranslation.java
  engine/src/main/java/com/ibm/engine/language/python/PythonSemantic.java
  engine/src/main/java/com/ibm/engine/serializer/ExportRules.java
  engine/src/main/java/com/ibm/engine/utils/DetectionStoreLogger.java
  java/src/main/java/com/ibm/plugin/translation/reorganizer/rules/MacReorganizer.java
  java/src/main/java/com/ibm/plugin/translation/translator/JavaTranslator.java
  java/src/main/java/com/ibm/plugin/translation/translator/contexts/JavaMacContextTranslator.java
  java/src/test/java/com/ibm/plugin/ExportJavaRulesToJsonTest.java
  java/src/test/java/com/ibm/plugin/TestBase.java
  java/src/test/java/com/ibm/plugin/utils/GenerateAssertsHelper.java
  mapper/src/main/java/com/ibm/mapper/mapper/ssl/json/JsonCipherSuites.java
  mapper/src/main/java/com/ibm/mapper/reorganizer/Reorganizer.java
  mapper/src/main/java/com/ibm/mapper/utils/Utils.java
  pom.xml
  python/src/main/java/com/ibm/plugin/translation/contexts/PythonKeyContextTranslator.java
  python/src/test/java/com/ibm/plugin/ExportPythonRulesToJsonTest.java
  python/src/test/java/com/ibm/plugin/TestBase.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveAliasImportTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveImportedStructTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveInnerFunctionCallTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveNameTypeAndValuesTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveScopeValuesTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveValuesWithHooksTest.java
  sonar-cryptography-plugin/src/main/java/com/ibm/plugin/CryptographyPlugin.java
  sonar-cryptography-plugin/src/main/java/com/ibm/plugin/OutputFileJob.java
Labels: enhancement

#60 Cherrypick/update logging
  common/pom.xml
  engine/pom.xml
  engine/src/main/java/com/ibm/engine/language/java/JavaDetectionEngine.java
  engine/src/main/java/com/ibm/engine/language/java/JavaLanguageSupport.java
  engine/src/main/java/com/ibm/engine/language/java/JavaLanguageTranslation.java
  engine/src/main/java/com/ibm/engine/language/python/PythonSemantic.java
  engine/src/main/java/com/ibm/engine/serializer/ExportRules.java
  engine/src/main/java/com/ibm/engine/utils/DetectionStoreLogger.java
  enricher/pom.xml
  java/pom.xml
  java/src/main/java/com/ibm/plugin/translation/reorganizer/rules/MacReorganizer.java
  java/src/main/java/com/ibm/plugin/translation/translator/JavaTranslator.java
  java/src/main/java/com/ibm/plugin/translation/translator/contexts/JavaMacContextTranslator.java
  java/src/test/java/com/ibm/plugin/ExportJavaRulesToJsonTest.java
  java/src/test/java/com/ibm/plugin/TestBase.java
  java/src/test/java/com/ibm/plugin/utils/GenerateAssertsHelper.java
  mapper/pom.xml
  mapper/src/main/java/com/ibm/mapper/mapper/ssl/json/JsonCipherSuites.java
  mapper/src/main/java/com/ibm/mapper/reorganizer/Reorganizer.java
  mapper/src/main/java/com/ibm/mapper/utils/Utils.java
  output/pom.xml
  pom.xml
  python/pom.xml
  python/src/main/java/com/ibm/plugin/translation/contexts/PythonKeyContextTranslator.java
  python/src/test/java/com/ibm/plugin/ExportPythonRulesToJsonTest.java
  python/src/test/java/com/ibm/plugin/TestBase.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveAliasImportTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveImportedStructTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveInnerFunctionCallTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveNameTypeAndValuesTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveScopeValuesTest.java
  python/src/test/java/com/ibm/plugin/rules/resolve/ResolveValuesWithHooksTest.java
  sonar-cryptography-plugin/pom.xml
  sonar-cryptography-plugin/src/main/java/com/ibm/plugin/CryptographyPlugin.java
  sonar-cryptography-plugin/src/main/java/com/ibm/plugin/OutputFileJob.java
Labels: enhancement

#62 update CBOM meta data
  output/src/main/java/com/ibm/output/Constants.java
  output/src/main/java/com/ibm/output/cyclondx/CBOMOutputFile.java
Labels: enhancement

#63 update CBOM meta data (#62)
  output/src/main/java/com/ibm/output/Constants.java
  output/src/main/java/com/ibm/output/cyclondx/CBOMOutputFile.java
Labels: enhancement

#64 update mvn publish
  .github/workflows/maven-publish.yml
Labels: github_actions

#69 trigger pipeline on dev branch too
  .github/workflows/maven.yml
Labels: github_actions

#77 Update README.md
  README.md
Labels: documentation

#46 Mention CBOM Viewer in the README
  README.md
Labels: documentation

#81 Remove java 11 reference
  README.md
Labels: documentation

#82 Fix GitHub Packages workflow
  .github/workflows/maven-publish.yml
Labels: github_actions
